# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

appmenu-update-available2 =
    .label = 更新が利用できます
    .buttonlabel = 更新をダウンロード
    .buttonaccesskey = D
    .secondarybuttonlabel = 後で
    .secondarybuttonaccesskey = m
appmenu-update-available-message2 = { -brand-shorter-name } の最新バージョンをダウンロード。
appmenu-update-manual2 =
    .label = 更新が利用できます
    .buttonlabel = ダウンロード
    .buttonaccesskey = D
    .secondarybuttonlabel = 今は行わない
    .secondarybuttonaccesskey = m
appmenu-update-manual-message2 = { -brand-shorter-name } を自動的に更新できませんでした。新しいバージョンをダウンロードしてください — 保存された情報やカスタマイズは維持されます。
appmenu-update-unsupported2 =
    .label = 更新できませんでした
    .buttonlabel = さらに詳しく
    .buttonaccesskey = L
    .secondarybuttonlabel = 閉じる
    .secondarybuttonaccesskey = m
appmenu-update-unsupported-message2 = お使いのオペレーティングシステムでは、最新バージョンの { -brand-shorter-name } は使用できません。
appmenu-update-restart2 =
    .label = 更新が利用できます
    .buttonlabel = 更新して再起動
    .buttonaccesskey = U
    .secondarybuttonlabel = 今は行わない
    .secondarybuttonaccesskey = m
appmenu-update-restart-message2 = { -brand-shorter-name } の最新バージョンを入手してください。 開いているタブとウィンドウは復元されます。
appmenu-update-other-instance =
    .label = 最新のバージョンの { -brand-shorter-name } に自動更新できません。
    .buttonlabel = 今すぐ { -brand-shorter-name } を更新
    .buttonaccesskey = U
    .secondarybuttonlabel = 後で
    .secondarybuttonaccesskey = N
appmenu-update-other-instance-message = 新しい { -brand-shorter-name } の更新が利用可能ですが、異なるプロファイルの { -brand-shorter-name } が実行されているため、インストールできません。 そちらを閉じて更新を続行するか、とにかく更新するかを選択してください (他のプロファイルは、再起動するまで正常に動作しない場合があります)。
appmenu-addon-private-browsing-installed2 =
    .buttonlabel = OK
    .buttonaccesskey = O
appmenu-addon-post-install-message3 = アプリケーションのメニューからアドオンとテーマを管理します。
appmenu-addon-post-install-incognito-checkbox =
    .label = この拡張機能がプライベート ウィンドウで動作するのを許可する
    .accesskey = A

appmenu-new-tab-controlled-changes =
    .label = 新しいタブの設定が変更されました。
    .buttonlabel = 変更を維持
    .buttonaccesskey = K
    .secondarybuttonlabel = 新しいタブを管理
    .secondarybuttonaccesskey = M
appmenu-homepage-controlled-changes =
    .label = ホームページの設定が変更されました。
    .buttonlabel = 変更を維持
    .buttonaccesskey = K
    .secondarybuttonlabel = ホームページを管理
    .secondarybuttonaccesskey = M
appmenu-tab-hide-controlled =
    .label = 非表示タブにアクセスします
    .buttonlabel = タブの非表示を維持
    .buttonaccesskey = K
    .secondarybuttonlabel =拡張機能を無効化
    .secondarybuttonaccesskey = D
