# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# DO NOT ADD THINGS OTHER THAN ERROR MESSAGES HERE.
# This file gets parsed into a JS dictionary of all known error message ids in
# gen_aboutneterror_codes.py . If we end up needing fluent attributes or
# refactoring them in some way, the script will need updating.

# Variables:
# $hostname (String) - Hostname of the website with SSL error.
# $errorMessage (String) - Error message corresponding to the type of error we are experiencing.
ssl-connection-error =
     { $hostname } への接続中にエラーが発生しました。 { $errorMessage }

# Variables:
# $error (string) - NSS error code string that specifies type of cert error. e.g. unknown issuer, invalid cert, etc.
cert-error-code-prefix = エラーコード: { $error }

psmerr-ssl-disabled = SSL プロトコルが無効になっているため、安全に接続できません。
psmerr-ssl2-disabled = サイトが古い安全でないバージョンの SSL プロトコルを使用しているため、安全に接続できません。

# This is a multi-line message.
psmerr-hostreusedissuerandserial =
    無効な証明書を受け取りました。サーバー管理者または電子メールの相手先に連絡して、次の情報を伝えてください:

    この証明書には、認証局によって発行された別の証明書と同じシリアル番号が含まれています。一意のシリアル番号を含む新しい証明書を取得してください。

ssl-error-export-only-server = 安全に通信できません。ピアは高度な暗号化をサポートしていません。
ssl-error-us-only-server =  安全に通信できません。ピアには、サポートされていない高度な暗号化が必要です。
ssl-error-no-cypher-overlap = ピアと安全に通信できません: 一般的な暗号化アルゴリズムがありません。
ssl-error-no-certificate = 認証に必要な証明書またはキーが見つかりません。
ssl-error-bad-certificate = ピアと安全に通信できません: ピアの証明書が拒否されました。
ssl-error-bad-client = サーバーはクライアントからの不正なデータに遭遇しました。
ssl-error-bad-server = クライアントがサーバーからの不正なデータに遭遇しました。
ssl-error-unsupported-certificate-type = サポートされていない証明書の形式です。
ssl-error-unsupported-version = ピアがサポートされていないバージョンのセキュリティ プロトコルを使用しています。
ssl-error-wrong-certificate = クライアント認証に失敗しました: 鍵データベースの秘密鍵が証明書データベースの公開鍵と一致しません。
ssl-error-bad-cert-domain = ピアと安全に通信できません: 要求されたドメイン名がサーバーの証明書と一致しません。
ssl-error-post-warning = 認識できない SSL エラー コードです。
ssl-error-ssl2-disabled = ピアはローカルで無効になっている SSL バージョン 2 のみをサポートしています。
ssl-error-bad-mac-read = SSL がメッセージ認証コードが正しくないレコードを受信しました。
ssl-error-bad-mac-alert = SSL ピアが正しくないメッセージ認証コードを報告しています。
ssl-error-bad-cert-alert = SSL ピアが証明書を検証できません。
ssl-error-revoked-cert-alert = SSL ピアが証明書を失効として拒否しました。
ssl-error-expired-cert-alert = SSL ピアが証明書を期限切れとして拒否しました。
ssl-error-ssl-disabled = 接続できません: SSL が無効になっています。
ssl-error-fortezza-pqg = 接続できません: SSL ピアが別の FORTEZZA ドメインにあります。
ssl-error-unknown-cipher-suite = 不明な SSL 暗号スイートが要求されました。
ssl-error-no-ciphers-supported = このプログラムでは暗号スイートが存在せず、有効になっていません。
ssl-error-bad-block-padding = SSL が不正なブロック パディングを含むレコードを受信しました。
ssl-error-rx-record-too-long = SSL が許容される最大長を超えるレコードを受信しました。
ssl-error-tx-record-too-long = SSL が許容される最大長を超えるレコードを送信しようとしました。
ssl-error-rx-malformed-hello-request =  SSL が不正な形式の Hello Request ハンドシェイク メッセージを受信しました。
ssl-error-rx-malformed-client-hello = SSL が不正な形式の Client Hello ハンドシェイク メッセージを受信しました。
ssl-error-rx-malformed-server-hello = SSL が不正な Server Hello ハンドシェイク メッセージを受信しました。
ssl-error-rx-malformed-certificate = SSL が不正な形式の証明書ハンドシェイク メッセージを受信しました。
ssl-error-rx-malformed-server-key-exch = SSL が不正な形式の Server Key Exchange ハンドシェイク メッセージを受信しました。
ssl-error-rx-malformed-cert-request = SSL が不正な形式の Certificate Request ハンドシェイク メッセージを受信しました。
ssl-error-rx-malformed-hello-done =  SSL が不正な Server Hello Done ハンドシェイク メッセージを受信しました。
ssl-error-rx-malformed-cert-verify = SSL が不正な形式の Certificate Verify ハンドシェイク メッセージを受信しました。
ssl-error-rx-malformed-client-key-exch = SSL は不正な Client Key Exchange ハンドシェイク メッセージを受信しました。
ssl-error-rx-malformed-finished = SSL が不正な形式の Finished ハンドシェイク メッセージを受信しました。
ssl-error-rx-malformed-change-cipher = SSL が不正な Change Cipher Spec レコードを受け取りました。
ssl-error-rx-malformed-alert =  SSL が不正な形式の Alert レコードを受信しました。
ssl-error-rx-malformed-handshake =  SSL が不正な形式の Handshake レコードを受信しました。
ssl-error-rx-malformed-application-data = SSL が不正な形式の Application Data レコードを受信しました。
ssl-error-rx-unexpected-hello-request = SSL が予期しない Hello Request ハンドシェイク メッセージを受信しました。
ssl-error-rx-unexpected-client-hello = SSL が予期しない Client Hello ハンドシェイク メッセージを受信しました。
ssl-error-rx-unexpected-server-hello = SSL が予期しない Server Hello ハンドシェイク メッセージを受信しました。
ssl-error-rx-unexpected-certificate = SSL が予期しない Certificate ハンドシェイク メッセージを受信しました。
ssl-error-rx-unexpected-server-key-exch = SSL が予期しない Server Key Exchange ハンドシェイク メッセージを受信しました。
ssl-error-rx-unexpected-cert-request = SSL が予期しない Certificate Request ハンドシェイク メッセージを受信しました。
ssl-error-rx-unexpected-hello-done = SSL が予期しない Server Hello Done ハンドシェイク メッセージを受信しました。
ssl-error-rx-unexpected-cert-verify = SSL が予期しない Certificate Verify ハンドシェイク メッセージを受信しました。
ssl-error-rx-unexpected-client-key-exch = SSL が予期しない Client Key Exchange ハンドシェイク メッセージを受信しました。
ssl-error-rx-unexpected-finished = SSL が予期しない Finished ハンドシェイク メッセージを受信しました。
ssl-error-rx-unexpected-change-cipher = SSL が予期しない Change Cipher Spec レコードを受信しました。
ssl-error-rx-unexpected-alert = SSL が予期しない Alert レコードを受信しました。
ssl-error-rx-unexpected-handshake = SSL が予期しない Handshake レコードを受信しました。
ssl-error-rx-unexpected-application-data = SSL が予期しない Application Data レコードを受信しました。
ssl-error-rx-unknown-record-type = SSL が不明なコンテンツ タイプのレコードを受信しました。
ssl-error-rx-unknown-handshake = SSL が不明なメッセージ タイプのハンドシェイク メッセージを受信しました。
ssl-error-rx-unknown-alert = SSL が説明が不明なアラート レコードを受信しました。
ssl-error-close-notify-alert = SSL ピアがこの接続を閉じました。
ssl-error-handshake-unexpected-alert = SSL ピアが予期しないハンドシェイク メッセージを受信しました。
ssl-error-decompression-failure-alert = SSL ピアが受信した SSL レコードを正常に解凍できませんでした。
ssl-error-handshake-failure-alert = SSL ピアが受け入れ可能な一連のセキュリティ パラメータをネゴシエートできませんでした。
ssl-error-illegal-parameter-alert = SSL ピアが受け入れられないコンテンツのハンドシェイク メッセージを拒否しました。
ssl-error-unsupported-cert-alert = SSL ピアが受信したタイプの証明書をサポートしていません。
ssl-error-certificate-unknown-alert = SSL ピアが受信した証明書に特定されていない問題がありました。
ssl-error-generate-random-failure = SSL の乱数ジェネレーターに障害が発生しました。
ssl-error-sign-hashes-failure = 証明書の検証に必要なデータにデジタル署名できません。
ssl-error-extract-public-key-failure = SSL はピアの証明書から公開鍵を抽出できませんでした。
ssl-error-server-key-exchange-failure = SSL Server Key Exchange ハンドシェイクの処理中に不明なエラーが発生しました。
ssl-error-client-key-exchange-failure = SSL Client Key Exchange ハンドシェイクの処理中に不明なエラーが発生しました。
ssl-error-encryption-failure = 選択された暗号スイートでのバルクデータ暗号化アルゴリズムに失敗しました。
ssl-error-decryption-failure = 選択された暗号スイートでのバルクデータ復号化アルゴリズムに失敗しました。
ssl-error-socket-write-failure = Attempt to write encrypted data to underlying socket failed.
ssl-error-md5-digest-failure = MD5 ダイジェスト関数が失敗しました。
ssl-error-sha-digest-failure = SHA-1 ダイジェスト関数が失敗しました
ssl-error-mac-computation-failure = MAC の計算に失敗しました。
ssl-error-sym-key-context-failure = 対称鍵コンテキストの作成に失敗しました。
ssl-error-sym-key-unwrap-failure = Client Key Exchange のメッセージで対称鍵をアンラップできませんでした。
ssl-error-pub-key-size-limit-exceeded = SSL Server attempted to use domestic-grade public key with export cipher suite.
ssl-error-iv-param-failure = PKCS11 code failed to translate an IV into a param.
ssl-error-init-cipher-suite-failure = Failed to initialize the selected cipher suite.
ssl-error-session-key-gen-failure = Client failed to generate session keys for SSL session.
ssl-error-no-server-key-for-alg = Server has no key for the attempted key exchange algorithm.
ssl-error-token-insertion-removal = PKCS#11 token was inserted or removed while operation was in progress.
ssl-error-token-slot-not-found = No PKCS#11 token could be found to do a required operation.
ssl-error-no-compression-overlap = Cannot communicate securely with peer: no common compression algorithm(s).
ssl-error-handshake-not-completed = Cannot initiate another SSL handshake until current handshake is complete.
ssl-error-bad-handshake-hash-value = Received incorrect handshakes hash values from peer.
ssl-error-cert-kea-mismatch = The certificate provided cannot be used with the selected key exchange algorithm.
ssl-error-no-trusted-ssl-client-ca = No certificate authority is trusted for SSL client authentication.
ssl-error-session-not-found = Client’s SSL session ID not found in server’s session cache.
ssl-error-decryption-failed-alert = Peer was unable to decrypt an SSL record it received.
ssl-error-record-overflow-alert = Peer received an SSL record that was longer than is permitted.
ssl-error-unknown-ca-alert = Peer does not recognize and trust the CA that issued your certificate.
ssl-error-access-denied-alert = Peer received a valid certificate, but access was denied.
ssl-error-decode-error-alert = Peer could not decode an SSL handshake message.
ssl-error-decrypt-error-alert = Peer reports failure of signature verification or key exchange.
ssl-error-export-restriction-alert = Peer reports negotiation not in compliance with export regulations.
ssl-error-protocol-version-alert = Peer reports incompatible or unsupported protocol version.
ssl-error-insufficient-security-alert = Server requires ciphers more secure than those supported by client.
ssl-error-internal-error-alert = Peer reports it experienced an internal error.
ssl-error-user-canceled-alert = Peer user canceled handshake.
ssl-error-no-renegotiation-alert = Peer does not permit renegotiation of SSL security parameters.
ssl-error-server-cache-not-configured = SSL server cache not configured and not disabled for this socket.
ssl-error-unsupported-extension-alert = SSL peer does not support requested TLS hello extension.
ssl-error-certificate-unobtainable-alert = SSL peer could not obtain your certificate from the supplied URL.
ssl-error-unrecognized-name-alert = SSL peer has no certificate for the requested DNS name.
ssl-error-bad-cert-status-response-alert = SSL peer was unable to get an OCSP response for its certificate.
ssl-error-bad-cert-hash-value-alert = SSL peer reported bad certificate hash value.
ssl-error-rx-unexpected-new-session-ticket = SSL が予期しない New Session Ticket ハンドシェイク メッセージを受信しました。
ssl-error-rx-malformed-new-session-ticket = SSL が不正な New Session Ticket ハンドシェイク メッセージを受信しました。
ssl-error-decompression-failure = SSL received a compressed record that could not be decompressed.
ssl-error-renegotiation-not-allowed = Renegotiation is not allowed on this SSL socket.
ssl-error-unsafe-negotiation = Peer attempted old style (potentially vulnerable) handshake.
ssl-error-rx-unexpected-uncompressed-record = SSL が予期しない非圧縮レコードを受信しました。
ssl-error-weak-server-ephemeral-dh-key = SSL received a weak ephemeral Diffie-Hellman key in Server Key Exchange handshake message.
ssl-error-next-protocol-data-invalid = SSL received invalid NPN extension data.
ssl-error-feature-not-supported-for-ssl2 = SSL 2.0 接続は SSL 機能をサポートしていません。
ssl-error-feature-not-supported-for-servers = サーバーは SSL 機能をサポートしていません。
ssl-error-feature-not-supported-for-clients = クライアントは SSL 機能をサポートしていません。
ssl-error-invalid-version-range = SSL バージョンの範囲が無効です。
ssl-error-cipher-disallowed-for-version = SSL peer selected a cipher suite disallowed for the selected protocol version.
ssl-error-rx-malformed-hello-verify-request = SSL が不正な形式の Hello Verify Request ハンドシェイク メッセージを受信しました。
ssl-error-rx-unexpected-hello-verify-request = SSL が予期しない Hello Verify Request ハンドシェイク メッセージを受信しました。
ssl-error-feature-not-supported-for-version = SSL feature not supported for the protocol version.
ssl-error-rx-unexpected-cert-status = SSL が予期しない Certificate Status ハンドシェイク メッセージを受信しました。
ssl-error-unsupported-hash-algorithm = Unsupported hash algorithm used by TLS peer.
ssl-error-digest-failure = Digest function failed.
ssl-error-incorrect-signature-algorithm = Incorrect signature algorithm specified in a digitally-signed element.
ssl-error-next-protocol-no-callback = Next Protocol Negotiation 拡張 (NP Extension) が有効になりましたが反応がありませんでした。
ssl-error-next-protocol-no-protocol = サーバーはクライアントが ALPN Extension によって知らせたプロトコルをサポートしていません。
ssl-error-inappropriate-fallback-alert = クライアントがサーバーがサポートするよりも低い TLS バージョンにダウングレードしたため、サーバーはハンドシェイクを拒否しました。
ssl-error-weak-server-cert-key = サーバー証明書に含まれる公開鍵が弱すぎます。
ssl-error-rx-short-dtls-read = DTLS レコード用のバッファに十分なスペースがありません。
ssl-error-no-supported-signature-algorithm = サポートされていない TLS 署名アルゴリズムによって構成されています。
ssl-error-unsupported-signature-algorithm = ピアはサポートされていない署名とハッシュ アルゴリズムの組み合わせを使用しています。
ssl-error-missing-extended-master-secret = The peer tried to resume without a correct extended_master_secret extension.
ssl-error-unexpected-extended-master-secret = The peer tried to resume with an unexpected extended_master_secret extension.
sec-error-io = An I/O error occurred during security authorization.
sec-error-library-failure = セキュリティ ライブラリに問題が発生しました。
sec-error-bad-data = セキュリティ ライブラリ: 不正なデータを受信しました。
sec-error-output-len = セキュリティ ライブラリ: 出力長のエラー。
sec-error-input-len = セキュリティ ライブラリで入力長のエラーが発生しました。
sec-error-invalid-args = セキュリティ ライブラリ: 無効な引数です。
sec-error-invalid-algorithm = セキュリティ ライブラリ: 無効なアルゴリズムです。
sec-error-invalid-ava = セキュリティ ライブラリ: 無効な AVA です。
sec-error-invalid-time = 時刻文字列の形式が正しくありません。
sec-error-bad-der = セキュリティ ライブラリ: DER でエンコードされたメッセージの形式が不適切です。
sec-error-bad-signature = ピアの証明書の署名が無効です。
sec-error-expired-certificate = ピアの証明書の有効期限が切れています。
sec-error-revoked-certificate = ピアの証明書が取り消されました。
sec-error-unknown-issuer = ピアの証明書の発行元が認識されていません。
sec-error-bad-key = ピアの公開鍵が無効です。
sec-error-bad-password = 入力されたセキュリティ パスワードが正しくありません。
sec-error-retry-password = 新しいパスワードが正しく入力されていません。もう一度やり直してください。
sec-error-no-nodelock = セキュリティ ライブラリ: ノードロックがありません。
sec-error-bad-database = セキュリティ ライブラリ: データベースが正しくありません。
sec-error-no-memory = セキュリティ ライブラリ: メモリの割り当てに失敗しました。
sec-error-untrusted-issuer = ユーザーによってピアの証明書の発行元は信頼しないと記録されています。
sec-error-untrusted-cert = ユーザーによってピアの証明書は信頼しないと記録されています。
sec-error-duplicate-cert = 証明書はデータベースに既に存在します。
sec-error-duplicate-cert-name = ダウンロードした証明書の名前が、データベースに既にある名前と重複しています。
sec-error-adding-cert = データベースへの証明書の追加中にエラーが発生しました。
sec-error-filing-key = Error refiling the key for this certificate.
sec-error-no-key = この証明書の秘密鍵が鍵データベースで見つかりません。
sec-error-cert-valid = この証明書は有効です。
sec-error-cert-not-valid = この証明書は無効です。
sec-error-cert-no-response = 証明書ライブラリ: 応答なし
sec-error-expired-issuer-certificate = The certificate issuer’s certificate has expired. Check your system date and time.
sec-error-crl-expired = The CRL for the certificate’s issuer has expired. Update it or check your system date and time.
sec-error-crl-bad-signature = The CRL for the certificate’s issuer has an invalid signature.
sec-error-crl-invalid = New CRL has an invalid format.
sec-error-extension-value-invalid = Certificate extension value is invalid.
sec-error-extension-not-found = Certificate extension not found.
sec-error-ca-cert-invalid = Issuer certificate is invalid.
sec-error-path-len-constraint-invalid = Certificate path length constraint is invalid.
sec-error-cert-usages-invalid = Certificate usages field is invalid.
sec-internal-only = **Internal ONLY module**
sec-error-invalid-key = The key does not support the requested operation.
sec-error-unknown-critical-extension = Certificate contains unknown critical extension.
sec-error-old-crl = New CRL is not later than the current one.
sec-error-no-email-cert = 暗号化も署名もされていません: 電子メール証明書がまだありません。
sec-error-no-recipient-certs-query = 暗号化されていません: 各受信者の証明書がありません。
sec-error-not-a-recipient = 復号化できません: 受信者ではないか、一致する証明書と秘密鍵が見つかりません。
sec-error-pkcs7-keyalg-mismatch = 復号化できません: 鍵の暗号化アルゴリズムが証明書と一致しません。
sec-error-pkcs7-bad-signature = 署名の検証に失敗しました: 署名者が見つからないか、見つかった署名者が多すぎるか、データが不適切または破損しています。
sec-error-unsupported-keyalg = サポートされていない、または不明な鍵のアルゴリズムです。
sec-error-decryption-disallowed = 復号化できません: 許可されていないアルゴリズムまたは鍵のサイズを使用して暗号化されています。
xp-sec-fortezza-bad-card = Fortezza card has not been properly initialized. Please remove it and return it to your issuer.
xp-sec-fortezza-no-card = No Fortezza cards Found
xp-sec-fortezza-none-selected = No Fortezza card selected
xp-sec-fortezza-more-info = Please select a personality to get more info on
xp-sec-fortezza-person-not-found = Personality not found
xp-sec-fortezza-no-more-info = No more information on that Personality
xp-sec-fortezza-bad-pin = Invalid Pin
xp-sec-fortezza-person-error = Couldn’t initialize Fortezza personalities.
sec-error-no-krl = No KRL for this site’s certificate has been found.
sec-error-krl-expired = The KRL for this site’s certificate has expired.
sec-error-krl-bad-signature = The KRL for this site’s certificate has an invalid signature.
sec-error-revoked-key = The key for this site’s certificate has been revoked.
sec-error-krl-invalid = New KRL has an invalid format.
sec-error-need-random = security library: need random data.
sec-error-no-module = security library: no security module can perform the requested operation.
sec-error-no-token = The security card or token does not exist, needs to be initialized, or has been removed.
sec-error-read-only = security library: read-only database.
sec-error-no-slot-selected = No slot or token was selected.
sec-error-cert-nickname-collision = A certificate with the same nickname already exists.
sec-error-key-nickname-collision = A key with the same nickname already exists.
sec-error-safe-not-created = error while creating safe object
sec-error-baggage-not-created = error while creating baggage object
xp-java-remove-principal-error = プリンシパルを削除できませんでした
xp-java-delete-privilege-error = 権限を削除できませんでした
xp-java-cert-not-exists-error = このプリンシパルには証明書がありません
sec-error-bad-export-algorithm = Required algorithm is not allowed.
sec-error-exporting-certificates = 証明書のエクスポート中にエラーが発生しました。
sec-error-importing-certificates = 証明書のインポート中にエラーが発生しました。
sec-error-pkcs12-decoding-pfx = インポートできません。デコードのエラー。ファイルが無効です。
sec-error-pkcs12-invalid-mac = インポートできません。MAC が無効です。パスワードが正しくないか、ファイルが破損しています。
sec-error-pkcs12-unsupported-mac-algorithm = インポートできません。MAC アルゴリズムはサポートされていません。
sec-error-pkcs12-unsupported-transport-mode = インポートできません。パスワードの整合性モードとプライバシーモードのみがサポートされています。
sec-error-pkcs12-corrupt-pfx-structure = インポートできません。ファイル構造が壊れています。
sec-error-pkcs12-unsupported-pbe-algorithm = インポートできません。暗号化アルゴリズムはサポートされていません。
sec-error-pkcs12-unsupported-version = インポートできません。ファイルバージョンはサポートされていません。
sec-error-pkcs12-privacy-password-incorrect = インポートできません。プライバシーパスワードが正しくありません。
sec-error-pkcs12-cert-collision = インポートできません。同じニックネームがデータベースに既に存在します。
sec-error-user-cancelled = The user pressed cancel.
sec-error-pkcs12-duplicate-data = インポートされていません。既にデータベースにあります。
sec-error-message-send-aborted = メッセージが送信されませんでした。
sec-error-inadequate-key-usage = Certificate key usage inadequate for attempted operation.
sec-error-inadequate-cert-type = Certificate type not approved for application.
sec-error-cert-addr-mismatch = Address in signing certificate does not match address in message headers.
sec-error-pkcs12-unable-to-import-key = インポートできません。秘密鍵のインポート中にエラーが発生しました。
sec-error-pkcs12-importing-cert-chain = インポートできません。証明書チェーンのインポート中にエラーが発生しました。
sec-error-pkcs12-unable-to-locate-object-by-name = エクスポートできません。ニックネームで証明書またはキーを見つけることができません。
sec-error-pkcs12-unable-to-export-key = エクスポートできません。秘密鍵が見つからずエクスポートできませんでした。
sec-error-pkcs12-unable-to-write = エクスポートできません。エクスポートするファイルを書き込めません。
sec-error-pkcs12-unable-to-read = インポートできません。インポートするファイルを読み取れません。
sec-error-pkcs12-key-database-not-initialized = エクスポートできません。鍵データベースが壊れているか削除されています。
sec-error-keygen-fail = Unable to generate public/private key pair.
sec-error-invalid-password = Password entered is invalid. Please pick a different one.
sec-error-retry-old-password = Old password entered incorrectly. Please try again.
sec-error-bad-nickname = Certificate nickname already in use.
sec-error-not-fortezza-issuer = Peer FORTEZZA chain has a non-FORTEZZA Certificate.
sec-error-cannot-move-sensitive-key = A sensitive key cannot be moved to the slot where it is needed.
sec-error-js-invalid-module-name = モジュール名が無効です。
sec-error-js-invalid-dll = モジュールのパス、またはファイル名が無効です
sec-error-js-add-mod-failure = モジュールを追加できません
sec-error-js-del-mod-failure = モジュールを削除できません
sec-error-old-krl = New KRL is not later than the current one.
sec-error-ckl-conflict = New CKL has different issuer than current CKL. Delete current CKL.
sec-error-cert-not-in-name-space = The Certifying Authority for this certificate is not permitted to issue a certificate with this name.
sec-error-krl-not-yet-valid = The key revocation list for this certificate is not yet valid.
sec-error-crl-not-yet-valid = The certificate revocation list for this certificate is not yet valid.
sec-error-unknown-cert = The requested certificate could not be found.
sec-error-unknown-signer = The signer’s certificate could not be found.
sec-error-cert-bad-access-location = The location for the certificate status server has invalid format.
sec-error-ocsp-unknown-response-type = OCSP レスポンスを完全にデコードすることはできません。未知のタイプです。
sec-error-ocsp-bad-http-response = OCSP サーバーが予期しない、または無効な HTTP データを返しました。
sec-error-ocsp-malformed-request = =OCSP サーバーはリクエストが破損しているか不正なフォーマットを検出しました。
sec-error-ocsp-server-error = OCSP サーバーで内部エラーが発生しました。
sec-error-ocsp-try-server-later = OCSP サーバーは後で再試行することを提案しました。
sec-error-ocsp-request-needs-sig = OCSP サーバーは、このリクエストに署名を要求しています。
sec-error-ocsp-unauthorized-request = OCSP サーバーは、このリクエストは無許可なため拒否しました。
sec-error-ocsp-unknown-response-status = OCSP サーバーが認識できないステータスを返しました。
sec-error-ocsp-unknown-cert = OCSP サーバーには証明書のステータスがありません。
sec-error-ocsp-not-enabled = この操作を実行する前に OCSP を有効にする必要があります。
sec-error-ocsp-no-default-responder = この操作を実行する前に OCSP のデフォルトのレスポンダーを設定する必要があります。
sec-error-ocsp-malformed-response = OCSP サーバーからの応答が壊れているか、不正なフォーマットです。
sec-error-ocsp-unauthorized-response = OCSP レスポンスの署名者には、この証明書のステータスを与える権限がありません。
sec-error-ocsp-future-response = OCSP レスポンスはまだ有効ではありません (将来の日付が含まれています)。
sec-error-ocsp-old-response = OCSP レスポンスに古い情報が含まれています。
sec-error-digest-not-found = The CMS or PKCS #7 Digest was not found in signed message.
sec-error-unsupported-message-type = The CMS or PKCS #7 Message type is unsupported.
sec-error-module-stuck = PKCS #11 module could not be removed because it is still in use.
sec-error-bad-template = Could not decode ASN.1 data. Specified template was invalid.
sec-error-crl-not-found = No matching CRL was found.
sec-error-reused-issuer-and-serial = You are attempting to import a cert with the same issuer/serial as an existing cert, but that is not the same cert.
sec-error-busy = NSS could not shutdown. Objects are still in use.
sec-error-extra-input = DER-encoded message contained extra unused data.
sec-error-unsupported-elliptic-curve = Unsupported elliptic curve.
sec-error-unsupported-ec-point-form = Unsupported elliptic curve point form.
sec-error-unrecognized-oid = Unrecognized Object Identifier.
sec-error-ocsp-invalid-signing-cert = OCSP レスポンスの OCSP 署名証明書が無効です。
sec-error-revoked-certificate-crl = Certificate is revoked in issuer’s certificate revocation list.
sec-error-revoked-certificate-ocsp = Issuer’s OCSP responder reports certificate is revoked.
sec-error-crl-invalid-version = Issuer’s Certificate Revocation List has an unknown version number.
sec-error-crl-v1-critical-extension = Issuer’s V1 Certificate Revocation List has a critical extension.
sec-error-crl-unknown-critical-extension = Issuer’s V2 Certificate Revocation List has an unknown critical extension.
sec-error-unknown-object-type = 不明なオブジェクト形式が指定されています。
sec-error-incompatible-pkcs11 = PKCS #11 driver violates the spec in an incompatible way.
sec-error-no-event = No new slot event is available at this time.
sec-error-crl-already-exists = CRL は既に存在します。
sec-error-not-initialized = NSS が初期化されていません。
sec-error-token-not-logged-in = The operation failed because the PKCS#11 token is not logged in.
sec-error-ocsp-responder-cert-invalid = Configured OCSP responder’s certificate is invalid.
sec-error-ocsp-bad-signature = OCSP レスポンスに無効な署名があります。
sec-error-out-of-search-limits = Cert validation search is out of search limits
sec-error-invalid-policy-mapping = Policy mapping contains anypolicy
sec-error-policy-validation-failed = Cert chain fails policy validation
sec-error-unknown-aia-location-type = Unknown location type in cert AIA extension
sec-error-bad-http-response = Server returned bad HTTP response
sec-error-bad-ldap-response = Server returned bad LDAP response
sec-error-failed-to-encode-data = Failed to encode data with ASN1 encoder
sec-error-bad-info-access-location = Bad information access location in cert extension
sec-error-libpkix-internal = Libpkix internal error occurred during cert validation.
sec-error-pkcs11-general-error = PKCS #11 モジュールが、回復不能なエラーが発生したことを示す
sec-error-pkcs11-function-failed = PKCS #11 モジュールが、要求された機能を実行できなかったことを示す CKR_FUNCTION_FAILED を返しました。 同じ操作を再試行すると成功する場合があります。
sec-error-pkcs11-device-error = PKCS #11 モジュールが CKR_DEVICE_ERROR を返しました。これはトークンまたはスロットで問題が発生したことを示しています。
sec-error-bad-info-access-method = Unknown information access method in certificate extension.
sec-error-crl-import-failed = CRL のインポート中にエラーが発生しました。
sec-error-expired-password = パスワードの有効期限が切れています。
sec-error-locked-password = パスワードはロックされています。
sec-error-unknown-pkcs11-error = 不明な PKCS #11 エラー。
sec-error-bad-crl-dp-url = Invalid or unsupported URL in CRL distribution point name.
sec-error-cert-signature-algorithm-disabled = The certificate was signed using a signature algorithm that is disabled because it is not secure.
mozilla-pkix-error-key-pinning-failure = サーバーは証明書のピン留め (HPKP) を使用していますが、ピンセットに一致する信頼できる証明書チェーンを構築できませんでした。ピンニング違反は上書きする事ができません。
mozilla-pkix-error-ca-cert-used-as-end-entity = The server uses a certificate with a basic constraints extension identifying it as a certificate authority. For a properly-issued certificate, this should not be the case.
mozilla-pkix-error-inadequate-key-size = The server presented a certificate with a key size that is too small to establish a secure connection.
mozilla-pkix-error-v1-cert-used-as-ca = サーバーの証明書を発行するためにトラストアンカーではない X.509 Version 1 証明書が使用されています。 X.509 Version 1 証明書は非推奨です。他の証明書の署名には使用しないでください。
mozilla-pkix-error-not-yet-valid-certificate = The server presented a certificate that is not yet valid.
mozilla-pkix-error-not-yet-valid-issuer-certificate = A certificate that is not yet valid was used to issue the server’s certificate.
mozilla-pkix-error-signature-algorithm-mismatch = The signature algorithm in the signature field of the certificate does not match the algorithm in its signatureAlgorithm field.
mozilla-pkix-error-ocsp-response-for-cert-missing = The OCSP response does not include a status for the certificate being verified.
mozilla-pkix-error-validity-too-long = The server presented a certificate that is valid for too long.
mozilla-pkix-error-required-tls-feature-missing = 必要な TLS 機能がありません。
mozilla-pkix-error-invalid-integer-encoding = The server presented a certificate that contains an invalid encoding of an integer. Common causes include negative serial numbers, negative RSA moduli, and encodings that are longer than necessary.
mozilla-pkix-error-empty-issuer-name = サーバーから発行者の識別名が無い証明書が提示されました。
mozilla-pkix-error-additional-policy-constraint-failed = An additional policy constraint failed when validating this certificate.
mozilla-pkix-error-self-signed-cert = 自己署名された証明書のため信頼できません。

